name: Build Baulko ⌚

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3.5.1
      - name: Build for Firefox and Chrome Web Store
        run: ./build.bat

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: Baulko Clock
          path: ./web-ext-artifacts/baulko_clock-2.0.2.zip
